-- MySQL Script generated by MySQL Workbench
-- Thu May 11 17:58:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rightwaydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rightwaydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rightwaydb` DEFAULT CHARACTER SET utf8 ;
USE `rightwaydb` ;

-- -----------------------------------------------------
-- Table `rightwaydb`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rightwaydb`.`contato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `assunto` VARCHAR(250) NULL,
  `mensagem` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rightwaydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rightwaydb`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `foto_perfil` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rightwaydb`.`universidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rightwaydb`.`universidade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(60) NOT NULL,
  `sigla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rightwaydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rightwaydb`.`curso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `capa` VARCHAR(300) NOT NULL,
  `universidade_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_curso_universidade_idx` (`universidade_id` ASC),
  CONSTRAINT `fk_curso_universidade`
    FOREIGN KEY (`universidade_id`)
    REFERENCES `rightwaydb`.`universidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rightwaydb`.`depoimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rightwaydb`.`depoimento` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `curso_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `comentario` VARCHAR(500) NOT NULL,
  INDEX `fk_curso_has_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_curso_has_usuario_curso1_idx` (`curso_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_curso_has_usuario_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `rightwaydb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `rightwaydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
